name: HeadHunter
main: com.gmail.scottmwoodward.headhunter.HeadHunter
version: 1.4.2

commands:
  spawnhead:
    description: Spawns a copy of the specified player's head into your inventory.
    usage: /spawnhead <playername>
    permission: headhunter.command.spawnhead
    
permissions:
  headhunter.command.spawnhead:
    description: Gives access to /spawnhead
    default: op
  headhunter.noDrop:
    description: With this permission a player's head will not drop
    default: false