# Items with the Looting enchantment can trigger additional drops. Each level of looting can allow up to one additional
# head to drop. For example, a Looting III sword has a maximum of four dropped heads.
ApplyLooting: true

# DisabledWorlds options allows you to disable worlds where the heads will drop. When a world is disabled there will be
# no drops at all in that world. World names must be exact and case sensitive.
#
# Example: DisabledWorlds: ['world_nether','world_the_end']
DisabledWorlds: []

# Determines if heads should drop only when killed by a player (true) or on any entity death (false)
DropOnlyOnPlayerKill: true
