main: com.binaryphoenixstudios.mc.headhunter.HeadHunterPlugin
version: 2.0.0
name: HeadHunter

commands:
    reload:
        description: Reloads HeadHunter.
        aliases: [hhreload, reloadhh, headhunterreload, reloadheadhunter]
        permission: headhunter.command.reload
        usage: Syntax - /reload
    spawnhead:
        description: Spawns the specified player head.
        aliases: [hhspawnhead, spawnheadhh]
        permission: headhunter.command.spawnhead
        usage: Syntax - /spawnhead <Player Name>
    version:
        description: Displays the version of the HeadHunter plugrin.
        aliases: [hhversion, versionhh]
        permission: headhunter.command.version
        usage: Syntax - /version

permissions:
    headhunter.command.reload:
        description: Gives access to HeadHunter's reload command.
        default: op
    headhunter.command.spawnhead:
        description: Gives access to HeadHunter's spawnhead command.
        default: op
    headhunter.command.version:
        description: Gives access to HeadHunter's version command.
        default: true